version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
  go-app:
    container_name: go-app
    build:
      context: ./back
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./back:/app
    ports:
      - 4444:4444